const { colors, fontFamily } = require('tailwindcss/defaultTheme')

module.exports = {
  theme: {
    colors: {
      ...colors,
      bg: 'var(--color-bg)',
      header: 'var(--color-header)',
      overlayBg: 'var(--color-overlay-bg)',
      card: 'var(--color-card)',
      cardHover: 'var(--color-card-hover)',
      cardElevated: 'var(--color-card-elevated)',
      cardBorder: 'var(--color-card-border)',
      input: 'var(--color-input)',
      column: 'var(--color-column)',
      heading: 'var(--color-heading)',
      textDarker: 'var(--color-text-darker)',
      textDark: 'var(--color-text-dark)',
      text: 'var(--color-text)',
      textLight: 'var(--color-text-light)',
      textLighter: 'var(--color-text-lighter)',
      placeholder: 'var(--color-placeholder)',
      primary: 'var(--color-primary)',
      primaryBg: 'var(--color-primary-bg)',
      primaryHover: 'var(--color-primary-hover)',
      primaryText: 'var(--color-primary-text)',
      buttonDefault: 'var(--button-default)',
      buttonDefaultHover: 'var(--button-default-hover)',
      successBg: 'var(--color-success-bg)',
      successHover: 'var(--color-success-hover)',
      successText: 'var(--color-success-text)',
      dangerBg: 'var(--color-danger-bg)',
      dangerHover: 'var(--color-danger-hover)',
      dangerText: 'var(--color-danger-text)',
    },
    fontFamily: {
      ...fontFamily,
      body: ['Poppins', ...fontFamily.sans],
    },
    fill: (theme) => ({
      primary: theme('colors.primary'),
      bg: theme('colors.bg'),
      heading: theme('colors.heading'),
      text: theme('colors.text'),
    }),
    stroke: (theme) => ({
      primary: theme('colors.primary'),
      bg: theme('colors.bg'),
      text: theme('colors.text'),
    }),
    extend: {},
  },
  variants: {},
  plugins: [],
}
